### ISSUE TITLE
MQ7 with Esp32 

### ISSUE THREAD

**Issue by dimitris1965** [fjebaker/MQ7#1]
Dear sir
Thank you for the great work.
I have a question.
Can I use the library with an Esp32?

**Comment by fjebaker** [comment]
Hello @dimitris1965 ! You should be able to -- it's been a while since I've worked with ESP32s, but if I recall correctly, you can use the Arduino library headers, in which case this code will work fine. Let me know how you get on!

**Comment by dimitris1965** [comment]
Thanks for the quick reply. 
 I have already tried it. I do not know if the analog reading is correct. The difference with ESP32 is that GPIOs are at 3.3V instead of 5.0V and analog readings are from 0 - 4095 instrad of 0 - 1023 for Arduino.

**Comment by fjebaker** [comment]
Ah I hadn't thought of that -- the [datasheet for MQ7](https://www.sparkfun.com/datasheets/Sensors/Biometric/MQ-7.pdf) says the operational voltage is 5V but later states that it can still operate accurately on 3.3V, so that should be okay.

As for the readings
https://github.com/fjebaker/MQ7/blob/a8e5fc6da307cc62a92fd40c27178caa9517d69d/src/MQ7.cpp#L30-L33

Adjusting line 32 to be `4095` should rectify that. I can add a commit that would let you set that dynamically if you like, else if you're happy updating the code locally, then that works too.

**Comment by dimitris1965** [comment]
I don't use the naked sensor!
I use the sensor module, so I can't use different voltage for analogreading and heater.
I think that is the problem!

**Comment by dimitris1965** [comment]
I think that I have solve my problem.
I have make a voltage divider from 5.0V to 3.3V and change the 1023 to 4095.
